### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by TomAtterton** [joonhocho/react-native-google-sign-in#1]
I can't seem to compile and keep getting the error 'react-native-google-sign-in/index.js: Unexpected token, expected ; (1:20)'

**Comment by pyko** [comment]
That's happening because the export statement in index.js is using "Export extensions transform"

To prevent this compile error, install babel plugin and add to .bablerc: http://babeljs.io/docs/plugins/transform-export-extensions/

**Comment by joonhocho** [comment]
@pyko Thanks I will update the document.

**Comment by joonhocho** [comment]
@pyko I changed the code to `module.exports = `, so the babel plugin shouldn't be needed anymore.
