### ISSUE TITLE
[feature] refresh access token

### ISSUE THREAD

**Issue by petergerdes** [joonhocho/react-native-google-sign-in#12]
A way to refresh and getting a new access token would be handy!

Just a promisify call with new token would be enough :)

**Comment by e-mk** [comment]
I don't have authentication server but also want to refresh token. but you are checking serverClientID before sending forceCodeForRefreshToken true value.

**Comment by joonhocho** [comment]
@ernest95 https://developers.google.com/android/reference/com/google/android/gms/auth/api/signin/GoogleSignInOptions.Builder#requestServerAuthCode(java.lang.String, boolean)
According to doc, `serverClientID` is required.

**Comment by stami** [comment]
You can use the `signInSilently` method to get refreshed accessToken when previous is expiring.

I created a PR of it: https://github.com/joonhocho/react-native-google-sign-in/pull/13

**Comment by joonhocho** [comment]
@stami @petergerdes Merged PR.
