### ISSUE TITLE
Wrong property name "RNGoogleSignIn"

### ISSUE THREAD

**Issue by reyhaan** [joonhocho/react-native-google-sign-in#15]
Please change it to "RNGoogleSignin" with a small letter "i", this wasted several hours of mine, damn!

Edit: It's giving undefined error with capital letter "I" as there is no such property on NativeModules when inspected using chrome debugger.

**Comment by stami** [comment]
I think it would be weird to name it otherwise as Google seems to have named it that way.

See imports at 
https://github.com/joonhocho/react-native-google-sign-in/blob/master/android/src/main/java/com/reactlibrary/googlesignin/RNGoogleSignInModule.java#L28

**Comment by reyhaan** [comment]
Actually the name of property on NativeModules is itself with the small letter "i". You can check that inside debugger, Also the properties used for color on RNGoogleSignin, i.e. dark, iconsOnly etc are also not defined when you see them in debugger. The file is:

https://github.com/joonhocho/react-native-google-sign-in/blob/master/js/GoogleSignIn.android.js#L10

**Comment by stami** [comment]
Sounds like you have had the @devfd library installed and there is some remainants of it. It has the native module named RNGoogleSignin with lowercase i. :)

**Comment by joonhocho** [comment]
@reyhaan I am not going to change it, as changing it will break everyone else who's already using this repo. Besides, as @stami said, I am following Google SDK's naming as much as possible, so I think it's better to leave it this way.
I am sorry that you've wasted several hours, but I've put several days for this project. Closing this issue.

**Comment by reyhaan** [comment]
@joonhocho No hard feelings, thanks for the library as I am using your version only. I didn't know that it's only me who's facing this problem.

**Comment by joonhocho** [comment]
@reyhaan Thanks for using it.
