### ISSUE TITLE
signoutpromise broken (iOS)

### ISSUE THREAD

**Issue by YousefED** [joonhocho/react-native-google-sign-in#16]
I think signout promise never resolves, because you're listening for disconnect events.

If just doing a sign out, the user will only be signed out locally and the disconnect events never raise.

Just calling .signOut doesn't work either, as this is dispatched async on iOS, so the function returns before the user is signed out.

For my own workaround, I've removed the async dispatch in signOut https://github.com/YousefED/react-native-google-sign-in/blob/master/ios/RNGoogleSignIn/RNGoogleSignIn.swift. Not sure this is the correct solution, but seems to be working for our use case now

**Comment by pipewrk** [comment]
I've experienced this too. My UI hangs on awating the Promise to resolve. Tapping the button again signs the user out

**Comment by cristian-milea** [comment]
same problem,

thanks @YousefED for quick-fix

**Comment by RalfNieuwenhuizen** [comment]
@joonhocho what's your view on this?

**Comment by joonhocho** [comment]
@YousefED If you remove async, are you saying it will raise disconnect event and thus resolved?

**Comment by YousefED** [comment]
@joonhocho honestly this is a while ago, I see we also made the following change to resolve this issue: https://github.com/YousefED/react-native-google-sign-in/commit/8227feb237d3aecaa4860038093814fc76fb1db1. Don't remember 100% but looks related :)

**Comment by YousefED** [comment]
@joonhocho the core of the issue is, is that:

await signOutPromise()

never resolves on iOS. the onDisconnect / onDisconnectError handlers are never called.

Do you have a suggested fix?

**Comment by calvinkei** [comment]
experiencing the same issue, signOutPromise never resolve (nor reject)

**Comment by joonhocho** [comment]
@YousefED @jasonnathan @frozenxis @RalfNieuwenhuizen @calcal12 

This issue has been fixed with new version.

Just upgraded to the latest Google SignIn SDK for iOS. (npm version 1.0.16)
Please follow new instructions carefully.
https://github.com/joonhocho/react-native-google-sign-in#ios
Also refer to ExampleApp if something is not working. I've tested ExampleApp and is working fine.
Feel free to reopen this issue if you cannot get it working.

**Comment by joonhocho** [comment]
FYI, `signout` should never call 'disconnect' events. `disconnect` should raise `disconnect` events. I fixed it accordingly.
