### ISSUE TITLE
Documentation Suggestion for RN 0.39

### ISSUE THREAD

**Issue by sachinrekhi** [joonhocho/react-native-google-sign-in#17]
Overall, awesome directions! Really appreciate the details on how to get the library up and running.

Since you mention that you tested on RN 0.39, I might encourage you to add a section in the in Getting Started section for iOS that says if you are still using RN 0.39, your {YourApp}/ios/{YourApp}-Bridging-Header.h needs to look like this instead:

#import "RCTBridgeModule.h"
#import "RCTViewManager.h"
#import "RCTEventEmitter.h"
#import <Google/SignIn.h>

**Comment by joonhocho** [comment]
@sachinrekhi Thanks for suggestion. Done!
