### ISSUE TITLE
Unkown status code 12501

### ISSUE THREAD

**Issue by gabsn** [joonhocho/react-native-google-sign-in#18]
When using your module, I get the following object instead of the correct user:
```javascript
Object {error: "unknown status code: 12501", code: 12501}
```

Do you have an idea why ?

**Comment by maggialejandro** [comment]
Same issue here, did you resolve it?

**Comment by TomAtterton** [comment]
@maggialejandro it's a permission issue [android guide old sign in](https://github.com/devfd/react-native-google-signin/blob/master/android-guide.md#d-after-the-sign-in-completes-i-get-the-following-error-error-code-12501-what-to-do-)

**Comment by maggialejandro** [comment]
@TomAtterton thanks Tom, I solved following this [steps](http://stackoverflow.com/questions/33583326/new-google-sign-in-android/37657942#37657942)
The problem was that I wasn't signing the debug APK
