### ISSUE TITLE
Compilation errors (iOS)

### ISSUE THREAD

**Issue by buskerone** [joonhocho/react-native-google-sign-in#19]
I'm having lot of errors when trying to compile the app (40 errors, file: RNGoogleSignIn.swift). Has anyone had the same problem? 
Xcode 8.2.1
RN 0.4

SS:
<img width="1021" alt="captura de pantalla 2017-03-01 a las 11 00 41 p m" src="https://cloud.githubusercontent.com/assets/2034112/23489885/c29e0c1e-fed3-11e6-8ad5-7a3be3a35e9b.png">

**Comment by joonhocho** [comment]
@buskerone It usually means that you haven't properly setup the bridging header. It may help to compare yours with `ExampleApp`.
Also make sure to open `.xcworkspace` not `.xcodeproj` after installing Cocoapods.

**Comment by joonhocho** [comment]
@buskerone 
Just upgraded to the latest Google SignIn SDK for iOS. (npm version 1.0.16)
Please follow new instructions carefully.
https://github.com/joonhocho/react-native-google-sign-in#ios
Also refer to ExampleApp if something is not working. I've tested ExampleApp and is working fine.
Feel free to reopen this issue if you cannot get it working.
