### ISSUE TITLE
Couple of updates to get things compiling etc

### ISSUE THREAD

**Issue by pyko** [joonhocho/react-native-google-sign-in#2]
Here are a few things I needed to do to get things loading properly

1. Needed to add: `classpath 'com.google.gms:google-services:3.0.0'` to `android/build.gradle` (otherwise it wouldn't even build the apk)

1. Fixed compile error about `react-native-google-sign-in/iindex.js`, by adding Export transform extension: http://babeljs.io/docs/plugins/transform-export-extensions/ (see: #1 )

1. My `react-native install` didn't seem to link things properly (it just added import to MainActivity.java), so had to manually modify `MainApplication.java` as below:

```
import com.reactlibrary.googlesignin.RNGoogleSignInPackage; // Add this
...
public class MainApplication extends Application implements ReactApplication {

@Override
    protected List<ReactPackage> getPackages() {
      return Arrays.<ReactPackage>asList(
          new MainReactPackage(),          
          new RNGoogleSignInPackage() // Add this
      );
    }
...
```

Also, would be useful to indicate which of the `configure` options are required and which ones are optional. So far only specified `scopes` and it seems to be working.

**Comment by joonhocho** [comment]
@pyko Thanks for reporting this. I don't know why `react-native install` does not link it automatically. I added some manual instructions to `README.md`.
