### ISSUE TITLE
Thanks it works but how can I make a log out? 

### ISSUE THREAD

**Issue by clearproof** [joonhocho/react-native-google-sign-in#22]
Btw I had a problem it only worked for me after adding this to my dependencies: 
compile(project(":react-native-google-sign-in")){
        exclude group: "com.google.android.gms" 
    }

please let me know how to make a log out 
Thanks

**Comment by joonhocho** [comment]
you can call `signOut` or `disconnect`.
You can refer to this doc for explanation.
https://developers.google.com/identity/sign-in/ios/api/interface_g_i_d_sign_in.html#a85f5b8fd48ffccc00b43214c2ae267cc

**Comment by clearproof** [comment]
cool thanks

**Comment by joonhocho** [comment]
@clearproof you're welcome
