### ISSUE TITLE
"Native module cannot be null" on iOS, RN v0.43.3

### ISSUE THREAD

**Issue by b3ngineer** [joonhocho/react-native-google-sign-in#26]
After linking the module into iOS, get this error: "Native module cannot be null".  

1.) Builds fine
      a. I do have an updated Bridge file
      b. Followed the instructions for iOS per Google
      c. Followed the instructions in the documentation for modifying my ios project
      d. I verified the pod is present after running 'pod install'
      e. ... No errors during build
2.) My Splash screen works
3.) And then RN is throwing the error in the module here:

{
            column = 39;
            file = "/{MY_APP_PATH_HIDDEN}/node_modules/react-native-google-sign-in/js/GoogleSignIn.ios.js";
            lineNumber = 14;
            methodName = "<unknown>";
        },

**Comment by salujaharkirat** [comment]
you can check this out https://github.com/joonhocho/react-native-google-sign-in/issues/14

**Comment by joonhocho** [comment]
@b3ngineer 
Just upgraded to the latest Google SignIn SDK for iOS. (npm version 1.0.16)
Please follow new instructions carefully.
https://github.com/joonhocho/react-native-google-sign-in#ios
Also refer to ExampleApp if something is not working. I've tested ExampleApp and is working fine.
Feel free to reopen this issue if you cannot get it working.
