### ISSUE TITLE
Question for the IOS framework

### ISSUE THREAD

**Issue by kathyLA** [joonhocho/react-native-google-sign-in#27]
Hi Thanks for the nice work.

Just wandering is there a reason need to wrap the sign in method in side the dipsatch.main.aysnc ?
?

**Comment by joonhocho** [comment]
@kathyLA I tried without the dispatch and there were some bugs that I can't remember, but I searched online and that was the solution suggested and it fixed the issue.

**Comment by kathyLA** [comment]
thanks for explanation!
