### ISSUE TITLE
react native configuration with name 'default' not found

### ISSUE THREAD

**Issue by RobinBobin** [joonhocho/react-native-google-sign-in#28]
Hi!

Having followed the installation guide step by step I kept getting the error mentioned in the subj when cleaning / building my app. It turned out that the lib subdirectory in node_modules **wasn't created** by `$ react-native install react-native-google-sign-in`. When I used `npm install` it worked like a charm. Linking is needed of course.

It seems to be a bug with `react-native install` but it took hours for me to find it out. Maybe you would find it appropriate to mention it in the readme.

Thanks for your work,
Robin.

**Comment by joonhocho** [comment]
Just upgraded to the latest Google SignIn SDK for iOS. (npm version 1.0.16)
Please follow new instructions carefully.
https://github.com/joonhocho/react-native-google-sign-in#ios
Also refer to ExampleApp if something is not working. I've tested ExampleApp and is working fine.
Feel free to reopen this issue if you cannot get it working.
