### ISSUE TITLE
Struggling to get the imports to work in objective C

### ISSUE THREAD

**Issue by timothylui** [joonhocho/react-native-google-sign-in#3]
Hi,

I've followed the guide, enabled swift in my OOTB objc project but I'm struggling to get the library to work in react native. I'm fairly certain it's because of an import problem.

The xcode project builds fine but when the javascript loads I get the following error.

```
Native module cannot be null.

NativeEventEmitter
    NativeEventEmitter.js:32
<unknown>
    GoogleSignIn.ios.js:12
loadModuleImplementation
    require.js:171
<unknown>
    index.js:1
loadModuleImplementation
    require.js:171
<unknown>
    LoginPage.js:16
loadModuleImplementation
    require.js:171
<unknown>
    RootRouter.js:14
loadModuleImplementation
    require.js:171
<unknown>
    index.ios.js:18
loadModuleImplementation
    require.js:171
guardedLoadModule
    require.js:116
global code
    require-0.js:1
```

I know you have only tested it in swift but I'd appreciate any help you could give getting it to work in objc.

Thanks

**Comment by joonhocho** [comment]
@timothylui Thanks for reporting. I will create an example project and try with objc environment.
Btw, which version of React Native are you using? Because `NativeEventEmitter` is fairly new api afaik.

**Comment by lukefanning** [comment]
I'm getting the exact same error. I'm using RN 0.40.0.

**Comment by joonhocho** [comment]
@timothylui @lukefanning I've created an ExampleApp and is working fine for me. I've also added some additional instructions to README.md 's iOS section.
Make sure that you have created a Swift Bridging Header.
Also, refer to the ExampleApp codes that I just added.

**Comment by timothylui** [comment]
Thanks, followed the updated guide and it works for me now :)

**Comment by joonhocho** [comment]
Awesome!

**Comment by lukefanning** [comment]
Thanks also got it working! I actually already had a correct Obj-C bridging header but it still wasn't working for me. I then noticed in your example app that the RNGoogleSignIn folder was yellow instead of blue. So I deleted the RNGoogleSignIn folder from my project and dragged the folder over again this time selecting "Create groups" instead of "Create references" and it worked OK.
