### ISSUE TITLE
Error with cocoa pods plz help

### ISSUE THREAD

**Issue by improve-ar** [joonhocho/react-native-google-sign-in#36]
Hi, im new in Xcode, im trying to install google firebase with cocoa pods and when going to compile I have this issue

Apple Mach-O Linker (ld) Error Group
clang: error: linker command failed with exit code 1 (use -v to see invocation)

when I run pod install I have this warnings too

[!] The `reactApp [Debug]` target overrides the `FRAMEWORK_SEARCH_PATHS` build setting defined in `Pods/Target Support Files/Pods-reactApp/Pods-reactApp.debug.xcconfig'. This can lead to problems with the CocoaPods installation
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.

please be very specific with yours answers, remember im noob with Xcode

**Comment by ghost** [comment]
Same issue I can't find the problem.
