### ISSUE TITLE
Is this still being mantained?

### ISSUE THREAD

**Issue by ShariqMush** [joonhocho/react-native-google-sign-in#40]
Just wanted to know if this module still works and if its being mantained so I can know if I need to find another module or fork this one. Thanks!

**Comment by grigored** [comment]
It works great for me

**Comment by joonhocho** [comment]
@ShariqMush Sorry, but I am currently fully occupied on other project. PRs are welcome!
FYI, I am using this on my app, tho it's not in production yet.

**Comment by joonhocho** [comment]
@ShariqMush 
Just upgraded to the latest Google SignIn SDK for iOS. (npm version 1.0.16)
Please follow new instructions carefully.
https://github.com/joonhocho/react-native-google-sign-in#ios
Also refer to ExampleApp if something is not working. I've tested ExampleApp and is working fine.
Feel free to reopen this issue if you cannot get it working.
