### ISSUE TITLE
New googlesignin pod

### ISSUE THREAD

**Issue by mcorner** [joonhocho/react-native-google-sign-in#43]
In order to match other dependencies that I have I had to switch to the newer google pod:
  pod 'GoogleSignIn'

In order to use that the imports have to be changed to:
#import <GoogleSignin/GoogleSignIn.h>

And the config in didFinishLaunchingWithOptions to:

  NSString *filePath = [[NSBundle mainBundle] pathForResource:@"GoogleService-Info" ofType:@"plist"];
  NSDictionary *plistDict = [NSDictionary dictionaryWithContentsOfFile:filePath];
  [GIDSignIn sharedInstance].clientID = [plistDict objectForKey:@"CLIENT_ID"];

Hopefully that helps someone.

**Comment by jamesalways** [comment]
You saved my life!!!! Thanks a lot!!!!! @mcorner

**Comment by grigored** [comment]
works great, can you open a pull request?

**Comment by gvillenave** [comment]
#52

**Comment by marcosluizfp** [comment]
This works great! Helped a lot! Thank you!

**Comment by marcosluizfp** [comment]
Opened pull request #54 to update documentation. Included this great tip there!

**Comment by diegomelo182** [comment]
Nice work dude! Thanks!

**Comment by calvinkei** [comment]
Awesome!! takes me hours to find the solution

**Comment by salujaharkirat** [comment]
I am getting error `Use of undeclared identifier 'GIDSignIn' ` after making the above changes. Any help please?

**Comment by andreecy** [comment]
After changing to new GoogleSignIn Pod, I am still getting error `'GoogleSignIn/GoogleSignIn.h' file not found` in `AppDelegate.h`
could someone help me please?

**Comment by joonhocho** [comment]
@mcorner @jamesalways @grigored @gvillenave @marcosluizfp @calcal12 @jinxac @andreecy 

Just upgraded to the latest Google SignIn SDK for iOS. (npm version 1.0.16)
Please follow new instructions carefully.
https://github.com/joonhocho/react-native-google-sign-in#ios
Also refer to ExampleApp if something is not working. I've tested ExampleApp and is working fine.
Feel free to reopen this issue if you cannot get it working.
