### ISSUE TITLE
[IOS] Missing iOS app ClientID - [SOLVED]

### ISSUE THREAD

**Issue by addingama** [joonhocho/react-native-google-sign-in#45]
Hi all,

I just want to share the info.

To make google signin work on iOS, you need to add `iosClientId` instead of `clientID` like in the documentation.

```
GoogleSignin.configure({
      iosClientId: '<your clientID>',
      scopes: ['openid', 'email', 'profile'],
      shouldFetchBasicProfile: true
})
```

Hope this help

**Comment by kyle-ssg** [comment]
Sorry but this is simply not true. I think you're looking at react-native-google-signin

**Comment by joonhocho** [comment]
@dashracer Can you confirm @kyle-ssg 's comment?

**Comment by joonhocho** [comment]
@dashracer Can I close this?

**Comment by khadkaPratik** [comment]
@dashracer what and where should i add to make google sign in work in my project??
