### ISSUE TITLE
SignIn idToken

### ISSUE THREAD

**Issue by tallen11** [joonhocho/react-native-google-sign-in#48]
The idToken I get from the SignIn response is null on Android but correct on iOS. It's successfully signing me in on Android as all of the other fields seem to be populated (eg I get an accessToken). This is my code for both iOS and Android: 
```
const config = {
    clientID: GoogleConfig.ClientIdIOS,
    scopes: ['profile', 'email', 'openid'],
    shouldFetchBasicProfile: true,
}

GoogleSignIn.configure(config).then(
    () => {
        GoogleSignIn.signInPromise().then(...)
    ...
```
Maybe I'm missing something I need in config? It seems in the documentation for Google SignIn I may need to include the serverClientID in the config?

**Comment by tallen11** [comment]
This was indeed the issue. To get an idToken on Android you need to specify the serverClientID in config, as the documentation states.

**Comment by scandinaro** [comment]
@tallen11 I tried adding just my serverClientID from the web app in the google api console as well as offlineAccess being set to true, but I'm still getting back null for the idToken.  Was there anything else you had to do?

**Comment by uendar** [comment]
how do we specify the serverClientID in config?
