### ISSUE TITLE
library failed to import bridging header

### ISSUE THREAD

**Issue by ivpusic** [joonhocho/react-native-google-sign-in#5]
I created another build configuration => "Staging", and when building with this configuration I get following error

```
failed to import bridging header '/Users/ipusic/xxxxxxx/node_modules/react-native-google-sign-in/ios/RNGoogleSignIn/RNGoogleSignIn-Bridging-Header.h'
```

**Comment by joonhocho** [comment]
@ivpusic I've tried with `Release` build config and it works fine. How is your `Staging` configuration different from `Release`?

**Comment by ivpusic** [comment]
just try duplicating release build, without doing any modificafions, and then run staging build

**Comment by joonhocho** [comment]
@ivpusic Can you try with Release build and see if it works for you? Also, make sure settings like `Header Search Paths` are applied to all your build configurations. You can check by clicking on the small arrow on the left of the settings name. Once you click on the arrow, it will expand to show settings for each build config.
If it works for `Debug`, but not for `Staging`, it means that some build settings are not consistent across configurations.

**Comment by ivpusic** [comment]
works for debug and release, header search paths are in place. strange

**Comment by joonhocho** [comment]
@ivpusic Yeah, sounds like it's problem with your `Staging` configuration, rather than that of this library. There must be some settings missing somewhere with your `Staging` configuration. I am closing this issue for now, but feel free to reopen it if you find anything helpful.
