### ISSUE TITLE
DeveloperERROR

### ISSUE THREAD

**Issue by trinadhkoya** [joonhocho/react-native-google-sign-in#50]
What is DEVELOPER ERROR?
i am getting {Error:DEVELOPER_ERROR,code:10}

**Comment by cranesandcaff** [comment]
In android studio, you can use the logs to get more information about the errors. It might be a bad configuration.

**Comment by trinadhkoya** [comment]
Yes,After adding SHA Key in the console.It works like a charm @cranesandcaff .Sorry for bad issue
