### ISSUE TITLE
Buildtime swift compiler errors in xCode

### ISSUE THREAD

**Issue by amitanmol** [joonhocho/react-native-google-sign-in#53]
I am facing buildtime swift compiler 41 errors in xCode, please see attached. I have Apple Swift version 3.1 (swiftlang-802.0.53 clang-802.0.42) on my mac.

Any help will be appreciable.
![screen shot 2017-09-08 at 3 50 00 pm](https://user-images.githubusercontent.com/8766865/30207620-bd4380b2-94ad-11e7-8725-a8d3708e1ff5.png)

**Comment by marcosluizfp** [comment]
I had the same problem and fixed it by creating a Swift file to the project and confirming the creation of a Bridging Header - this way XCode is properly configured to use the Bridging Header.

**Comment by joonhocho** [comment]
@amitanmol It seems you have not correctly setup your Swift Bridging header for your project. It's very fragile and can be painful, but try to follow Apple's instruction on how to create a swift bridge header. You can take a look at `ExampleApp` for the reference.

**Comment by amitanmol** [comment]
Hi @marcosluizfp and @joonhocho, 

Thanks for quick reply. 

I have created swift bridge header file again and linked in build settings also, now it is liked and working. But I am getting some other buildtime swift compiler errors now, please see attached. 

![screen shot 2017-09-14 at 4 44 54 pm](https://user-images.githubusercontent.com/8766865/30427344-1bec9f54-996d-11e7-966f-3b33b728d27e.png)

**Comment by joonhocho** [comment]
@amitanmol It should be `@objc(...)` did you accidentally change it?

**Comment by amitanmol** [comment]
@joonhocho No I did not change any thing. Just followed the steps https://github.com/joonhocho/react-native-google-sign-in#ios

**Comment by joonhocho** [comment]
https://github.com/joonhocho/react-native-google-sign-in/blob/master/ios/RNGoogleSignIn/RNGoogleSignInEvents.swift#L10

See how there is `@objc`. I think you mis editted your source.

**Comment by amitanmol** [comment]
@joonhocho I did not mis edited, I installed the component through npm. 

Anyway, I did download your latest code from git and replaced RNGoogleSignIn folder in mine and it worked.

Thanks for your quick support.

**Comment by joonhocho** [comment]
@amitanmol np! i will close this.
