### ISSUE TITLE
'Google/SignIn.h' file not found

### ISSUE THREAD

**Issue by xralphack** [joonhocho/react-native-google-sign-in#57]
I created Swift Bridging Header 

#import <Google/SignIn.h> still has error 

'Google/SignIn.h' file not found occurred in Bridging Header
 
anyone can help?

**Comment by cloudle** [comment]
I have the same problem.. on iOs.. by the way, the link to article "create Swift Bridging Header" is broken (that page not work anymore)..

**Comment by cloudle** [comment]
Hey @xralphack, have a look at #43.. that one saved my life ;)

In summary, the **GoogleSignIn** pod was updated, so.. we'll need to:
1. Change `#import <Google/SignIn.h>` => `#import <GoogleSignin/GoogleSignIn.h>`

2. Change the config in **didFinishLaunchingWithOptions** to:

> NSString *filePath = [[NSBundle mainBundle] pathForResource:@"GoogleService-Info" ofType:@"plist"];
> NSDictionary *plistDict = [NSDictionary dictionaryWithContentsOfFile:filePath];
> [GIDSignIn sharedInstance].clientID = [plistDict objectForKey:@"CLIENT_ID"];
>

**Comment by salujaharkirat** [comment]
I am getting error Use of undeclared identifier 'GIDSignIn' after making the above changes. Any help please?

**Comment by cloudle** [comment]
@jinxac, not really sure about it, but you could check (you're very likely forget number 3):
**1. Make sure your pod is up to date with latest** 
```
pod 'GoogleSignIn'
```

**2. Double check your [app?]-Bridgin-Header.h file - should look like this:**

```
#ifndef app_Bridging_Header_h
#define app_Bridging_Header_h

#import <React/RCTBridgeModule.h>
#import <React/RCTViewManager.h>
#import <React/RCTEventEmitter.h>
#import <GoogleSignin/GoogleSignIn.h>

#endif /* app_Bridging_Header_h */
```

**3. Did you forget to add is in the end of your `AppDelegate.m`?:**
```
- (BOOL)application:(UIApplication *)application
            openURL:(NSURL *)url
            options:(NSDictionary<UIApplicationOpenURLOptionsKey,id> *)options {
  BOOL handled = [[GIDSignIn sharedInstance] handleURL:url
                                     sourceApplication:options[UIApplicationOpenURLOptionsSourceApplicationKey]
                                            annotation:options[UIApplicationOpenURLOptionsAnnotationKey]];
  return handled;
}

- (BOOL)application:(UIApplication *)application
            openURL:(NSURL *)url
  sourceApplication:(NSString *)sourceApplication
         annotation:(id)annotation {
  if ([[GIDSignIn sharedInstance] handleURL:url
                          sourceApplication:sourceApplication
                                 annotation:annotation]) {
    return YES;
  }
  return YES;
}
```

**Comment by andreecy** [comment]
After changing to new GoogleSignIn Pod, I am still getting error `'GoogleSignIn/GoogleSignIn.h' file not found` in `AppDelegate.h`
could someone help me please?

**Comment by joonhocho** [comment]
@andreecy  @cloudle @jinxac @xralphack 
Just upgraded to the latest Google SignIn SDK for iOS. (npm version 1.0.16)
Please follow new instructions carefully.
https://github.com/joonhocho/react-native-google-sign-in#ios
Also refer to ExampleApp if something is not working. I've tested ExampleApp and is working fine.
Feel free to reopen this issue if you cannot get it working.

**Comment by tmaly1980** [comment]
@joonhocho You say in the documentation to NOT use the POD.... So where does GoogleSignIn/GoogleSignIn.h come from? I see it in GoogleSignIn.framework, but am not sure why it's not showing up. I get the GoogleSignIn/GoogleSignIn.h file not found error.

**Comment by peeyush1234** [comment]
@joonhocho I had the same issue of GoogleSignIn/GoogleSignIn.h file not found. I was getting this error because I did not add the path of google_signin_sdk_4_X_X  to "Framework Search Paths" settings inside "Build Settings" of the project. After adding the path, the project build succeeded.

**Comment by Prashant-Mutnale** [comment]
@andreecy  I'm still getting this error even after following the procedures perfectly could someone help me please?
