### ISSUE TITLE
iOS GGLContext issue 

### ISSUE THREAD

**Issue by harshsrivastavaglobussoft** [joonhocho/react-native-google-sign-in#59]
When building its showing error 
installed pods
  pod 'GoogleSignIn'
  pod 'GoogleAnalytics'
Xcode 8.3.2 
"react": "^16.0.0-alpha.12",
"react-native": "^0.48.3",
![screenshot at nov 09 15-44-27](https://user-images.githubusercontent.com/24026483/32600320-46a1fb58-c565-11e7-93e6-c8212613d52e.png)
"react-native-google-sign-in": "0.0.8",

**Comment by joonhocho** [comment]
@harshsrivastavaglobussoft 

Just upgraded to the latest Google SignIn SDK for iOS. (npm version 1.0.16)
Please follow new instructions carefully.
https://github.com/joonhocho/react-native-google-sign-in#ios
Also refer to ExampleApp if something is not working. I've tested ExampleApp and is working fine.

**Comment by joonhocho** [comment]
Feel free to reopen this issue if new version did not fix it.

**Comment by harshsrivastavaglobussoft** [comment]
@joonhocho 
ok

**Comment by harshsrivastavaglobussoft** [comment]
@joonhocho 
it worked thanks
