### ISSUE TITLE
I can't get the iOS project to build

### ISSUE THREAD

**Issue by sakarit-zz** [joonhocho/react-native-google-sign-in#6]
It gives me an error like this:

```
ld: warning: directory not found for option '-F/Users/sakarit/repositories/xxx/ios/Build/Products/Debug-iphonesimulator/GTMOAuth2'
ld: warning: directory not found for option '-F/Users/sakarit/repositories/xxx/ios/Build/Products/Debug-iphonesimulator/GTMSessionFetcher'
ld: warning: directory not found for option '-F/Users/sakarit/repositories/xxx/ios/Build/Products/Debug-iphonesimulator/GoogleToolboxForMac'
ld: framework not found GTMOAuth2
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

Do you have any idea what could be wrong?

**Comment by sakarit-zz** [comment]
Okay I found out what was wrong. The thing that I did was that I closed the Xcode, installed the cocoapods and then reopened my project with the original .xcodeproj file instead of the new .xcworkspace file. Of course it didn't not work. 😄

Maybe this could be added to the installing instructions!

**Comment by joonhocho** [comment]
@sakarit Added to README.md :)
