### ISSUE TITLE
Duplicate symbols when integrating Firebase and Google sign-in 

### ISSUE THREAD

**Issue by BricePissard** [joonhocho/react-native-google-sign-in#63]
When it comes to build more sophisticated apps we need to integrate Google Sign-In with Firebase. Firebase should better be installed through Pod.
Ex:
```shell
...
pod 'Firebase/Core'
pod 'Firebase/Performance'
pod 'Firebase/Crash'
pod 'Firebase/Auth'
pod 'Firebase/Analytics'
...
```

But Firebase/Core includes `GTMSessionFetcher` and `GoogleToolboxForMac` in its compiled library.
So it ended to have two compiled duplicated libraries in the SDK framework and the Pod libs in:

`${PROJECT_DIR}/ios/{YourApp}/google_signin_sdk_4_1_1/GoogleSignIn.framework` 
and
`${PROJECT_DIR}/ios/Pods/GoogleToolboxForMac`
`${PROJECT_DIR}/ios/Pods/GTMSessionFetcher`

it seems possible to remove from within the SDK framework the duplicated libs as explained here:
https://stackoverflow.com/questions/41217839/duplicate-symbols-when-integrating-firebase-and-google-sign-in-sdks-manually-wit

All the process works fine, but I cant make it works in the app. The compilation pass trough the previous Duplicated lib error, but onces launched in react-native, the native module is not available:

```javascript
const {
  RNGoogleSignIn,
  RNGoogleSignInEvents,
} = NativeModules;

const emitter = new NativeEventEmitter(RNGoogleSignInEvents);
``` 

![screen shot 2017-12-01 at 9 39 03 am](https://user-images.githubusercontent.com/4115874/33474560-84a222a8-d67b-11e7-8a59-b40da1315f7a.png 'Native module can not be null in GoogleSignIn.ios.js:14:16')

So at the end, we have to choose between either Google SignIn or Google Firebase but, at the time of now, it doesn't seem to be possible to have them both in react-native.

I've scrupulously followed the installation process but I can't be sure this issue come from the edited GoogleSignIn.framework or the Swift Header detection to compile the react-native-google-sign-in module.

- not having Firebase working with GoogleSignIn in react-native is quite a big issue?
- not being able to install them both through Pod is also quite a big issue?

Is anyone have passed through this problem? can we fix it?

**Comment by BricePissard** [comment]
I've fix the problem.

Even if I new it before I didn't controlled that while adding the `RNGoogleSignIn` folder into the XCode App environment, the `Options` were not setup correctly: `Copy items if needed` checked and `Create groups` selected:


![screen-shot-2017-12-01-at-3 13 33-pm](https://user-images.githubusercontent.com/4115874/33486626-161fa1f4-d6ab-11e7-8474-99b6a2c52a7c.png)
 
Now with the previous description I have Firebase with Analytics, Crash, Performance and Auth working in parallel with CocoaPod files shared between Google SignIn and Firebase.

I've submit a PR commenting the process in the Readme.rm file #64

**Comment by tmaly1980** [comment]
I couldn't get this working but what I did do was follow the CocoaPods based install instead, since Firebase was CocoaPods based - 

https://developers.google.com/identity/sign-in/ios/start-integrating

Worked fine for me.

**Comment by ankitladhania** [comment]
If someone faces this same problem, I solved it using this [SO post](https://stackoverflow.com/questions/41217839/duplicate-symbols-when-integrating-firebase-and-google-sign-in-sdks-manually-wit), but I had to keep the following rather than the ones suggested in the post

<img width="479" alt="final kept objects" src="https://user-images.githubusercontent.com/6463117/35348135-264a4ffc-015d-11e8-8bf2-11329f13056b.png">

I'm using **GoogleSignIn SDK 4.1.1**
and **Firebase v4.8.0**
