### ISSUE TITLE
ld: 196 duplicate symbols for architecture x86_64

### ISSUE THREAD

**Issue by gimwee** [joonhocho/react-native-google-sign-in#70]
Hey guys, follow the instruction but bump into the following error, any help would be appreciated , TIA :)

<img width="585" alt="screen shot 2018-01-18 at 2 59 57 pm" src="https://user-images.githubusercontent.com/20056241/35080292-ac4dcb58-fc60-11e7-8c90-6d8c38905982.png">

**Comment by matyasfodor** [comment]
@gimwee I'm having the same issue. Why did you close it?

**Comment by oriharel** [comment]
same here

**Comment by calvinkei** [comment]
same here

**Comment by YuriiSrohyi** [comment]
@gimwee same here

**Comment by drailanjohngss** [comment]
same here could somebody help us!

**Comment by oriharel** [comment]
O ended up following this SO answer and although a bit long, solves this issue.
https://stackoverflow.com/questions/41217839/duplicate-symbols-when-integrating-firebase-and-google-sign-in-sdks-manually-wit

**Comment by matyasfodor** [comment]
@oriharel That's what I ended up doing as well. Although, the provided bash script didn't work.

**Comment by oriharel** [comment]
@matyasfodor need to make sure it's applied on the GoogleSignInDependencies file which is INSIDE the bundle

**Comment by matyasfodor** [comment]
Never mind my answer, there was a bash script posted which supposed to do all these black magic automatically but now I can't find it.
