### ISSUE TITLE
Project obsolete?

### ISSUE THREAD

**Issue by nuthinking** [joonhocho/react-native-google-sign-in#88]
Doesn't seem to work with the latest version of React / Xcode / iOS / Google SDK.

**Comment by pkantsedalov** [comment]
@nuthinking Can't say so. I successfully implemented a solution using this lib. The only obsolete thing here is README - the link to Swift bridge creation is really obsolete.

**Comment by arju88nair** [comment]
@pkantsedalov How did you do it? Google doesn't provide google-services.json anymore right?

**Comment by pkantsedalov** [comment]
@arju88nair I didn't even download anything from Google. Just copypasted files from current repo to my native sources and added Swift bridge. After that everything works fine.

**Comment by nuthinking** [comment]
So it must be me. Thanks for the info!
