### ISSUE TITLE
ld: library not found for -lRNGoogleSignin

### ISSUE THREAD

**Issue by ghodsizadeh** [joonhocho/react-native-google-sign-in#95]
I think I done every thing that you write in IOS installation but ,when I run react-native run-ios I see this error:
`ld: library not found for -lRNGoogleSignin`
Is there something that I missed during installation of RNGoogleSignin? 
How can I figure it out?

**Comment by vaskomichal** [comment]
How you fix this problem ? :(

**Comment by ghodsizadeh** [comment]
its all about linking,
please try manual linking and check if the error disappears or not.
